version: 2
jobs:
  build:
    docker: # use the docker executor type; machine and macos executors are also supported
      - image: circleci/node:8.9.4 # the primary container, where your job's commands are run
    steps:
      - checkout # check out the code in the project directory
      - run:
            name: install jest
            command: npm install jest
      - run:
            name: run unit tests
            command: npm run test
      - run:
            name: run e2e tests
            command: npm run test:e2e
      - run:
            name: run cov tests
            command: npm run test:cov
    
